#!/usr/bin/env bash
#==============================================================================
# tests/test_state.sh — Mock-$TOOLKIT_ROOT exercise for lib/state.sh
#==============================================================================
# Builds a populated $TOOLKIT_ROOT under a temp dir, sources lib/state.sh, and
# prints every public-API call's output so Jason can eyeball parsing.
#==============================================================================

set -o pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
LIB="$HERE/../lib/state.sh"

TMP=$(mktemp -d -t stuckr-state-XXXXXX)
trap 'rm -rf "$TMP"' EXIT
export TOOLKIT_ROOT="$TMP"

#------------------------------------------------------------------------------
# Build mock layout
#------------------------------------------------------------------------------

# --- Target A: full state (the main case) ---
T1=10.10.11.42
mkdir -p "$TMP/targets/$T1/"{recon,web,ad,evidence,state}

cat > "$TMP/targets/$T1/recon/nmap.txt" <<'EOF'
# Nmap 7.94 scan initiated
Nmap scan report for 10.10.11.42
Host is up (0.034s latency).
Not shown: 996 closed tcp ports (reset)
PORT     STATE SERVICE      VERSION
22/tcp   open  ssh          OpenSSH 8.4p1 Debian 5+deb11u1 (protocol 2.0)
80/tcp   open  http         Apache httpd 2.4.51 ((Debian))
139/tcp  open  netbios-ssn  Samba smbd 4.10.0
445/tcp  open  microsoft-ds Samba smbd 4.10.0
8080/tcp open  http-proxy
9999/tcp filtered abyss
Running: Linux 5.X
OS details: Linux 5.4 - 5.10
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel
EOF

cat > "$TMP/targets/$T1/recon/smb.txt" <<'EOF'
# nxc smb output
SMB         10.10.11.42     445   FILESRV    [+] domain.local\
Sharename       Type      Comment
ADMIN$
IPC$
backup
public
EOF

cat > "$TMP/targets/$T1/web/feroxbuster.txt" <<'EOF'
200      GET      120l    45w    1234c http://10.10.11.42/login
200      GET      80l     30w    900c  http://10.10.11.42/admin
301      GET      0l      0w     0c    http://10.10.11.42/api => http://10.10.11.42/api/
404      GET      9l      30w    276c  http://10.10.11.42/uploads
EOF

cat > "$TMP/targets/$T1/web/gobuster.txt" <<'EOF'
===============================================================
Gobuster v3.6
===============================================================
/login                (Status: 200) [Size: 1234]
/admin                (Status: 200) [Size: 900]
/uploads              (Status: 301) [Size: 0] [--> /uploads/]
/dashboard            (Status: 401) [Size: 0]
EOF

cat > "$TMP/targets/$T1/web/vhosts.txt" <<'EOF'
staging.corp.local
dev.corp.local
EOF

cat > "$TMP/targets/$T1/ad/users.txt" <<'EOF'
jdoe
asmith
svc_backup
EOF

cat > "$TMP/targets/$T1/ad/computers.txt" <<'EOF'
DC01
FILESRV
WS-01
EOF

# Foothold present, no privesc proof yet.
echo "abc123flag" > "$TMP/targets/$T1/evidence/local.txt"

cat > "$TMP/targets/$T1/state/sentinels.log" <<EOF
2026-05-20T14:33:12 smb-no-anon
2026-05-20T14:35:01 web-no-vhosts
2026-05-20T14:36:44 smb-no-anon
EOF

cat > "$TMP/targets/$T1/state/next_steps.txt" <<'EOF'
# Generated by recon.sh
[x] web-feroxbuster-common
[x] smb-anon-listing
[ ] web-tech-fingerprint
[ ] ssh-version-check
some prose that should not register as a slug
1. ad-enum-smb-null-session
EOF

# --- Target B: empty state (fallback case A) ---
T2=10.10.11.99
mkdir -p "$TMP/targets/$T2"

# --- Target C: services only, no sentinels ---
T3=10.10.11.55
mkdir -p "$TMP/targets/$T3/recon"
cat > "$TMP/targets/$T3/recon/nmap.txt" <<'EOF'
PORT     STATE SERVICE       VERSION
3389/tcp open  ms-wbt-server Microsoft Terminal Services
5985/tcp open  http          Microsoft HTTPAPI httpd 2.0
OS details: Windows Server 2019
EOF

# --- Global state ---
# creds.txt is the authoritative 6-field pipe schema written by
# state_append_cred (TIMESTAMP|PROTO|HOST|USER|CRED|NOTE), read back as
# cred=USER:CRED — NOT the legacy creds/creds.txt path. Includes a duplicate
# (different timestamp) for the dedupe path, a colon-bearing NT hash, and a
# malformed line that must be skipped (NF<6).
mkdir -p "$TMP/ad"
cat > "$TMP/creds.txt" <<'EOF'
# TIMESTAMP | PROTO | HOST | USER | CRED | NOTE
2026-05-20 16:00:00 | exploit  | -               | jdoe                 | Summer2026! | via-targetcheckr
2026-05-20 16:01:00 | crackr   | 10.10.11.42     | admin                | Welcome1 | cracked
2026-05-20 16:02:00 | adr      | DC01            | svc_backup           | aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0 | nthash
2026-05-20 16:03:00 | exploit  | -               | jdoe                 | Summer2026! | dup-different-timestamp
this line is malformed and must be skipped
EOF
echo "corp.local" > "$TMP/ad/domain.txt"
echo "10.10.11.10" > "$TMP/ad/dc.txt"

#------------------------------------------------------------------------------
# Run tests
#------------------------------------------------------------------------------

# shellcheck disable=SC1090
source "$LIB"

bar() { printf '\n==== %s ====\n' "$*"; }

bar "state_list_targets"
state_list_targets

bar "state_read_global"
state_read_global

bar "state_read_target $T1   (full state, with foothold)"
state_read_target $T1

bar "state_read_target $T2   (empty: no enumeration files)"
state_read_target $T2

bar "state_read_target $T3   (services only, no sentinels)"
state_read_target $T3

bar "state_emit_empty $T1 web-no-dirs   (append + reread sentinels)"
state_emit_empty $T1 web-no-dirs
echo "-- sentinels.log after emit:"
cat "$TMP/targets/$T1/state/sentinels.log"
echo "-- state_read_target sentinel lines after emit:"
state_read_target $T1 | grep ^sentinel=

#------------------------------------------------------------------------------
# Assertions — state_read_global creds reader (authoritative creds.txt schema)
#------------------------------------------------------------------------------
bar "ASSERT state_read_global creds reader (USER:CRED, dedupe, skip malformed)"
APASS=0; AFAIL=0
ck() { if [[ "$2" == "$3" ]]; then printf '  [PASS] %s\n' "$1"; APASS=$((APASS+1));
       else printf '  [FAIL] %s (got %s want %s)\n' "$1" "$2" "$3"; AFAIL=$((AFAIL+1)); fi; }

G=$(state_read_global)
ck "cred jdoe:Summer2026!"  "$(grep -cxF 'cred=jdoe:Summer2026!' <<<"$G")" 1   # also proves dedupe
ck "cred admin:Welcome1"    "$(grep -cxF 'cred=admin:Welcome1' <<<"$G")" 1
ck "cred colon-bearing hash" \
   "$(grep -cxF 'cred=svc_backup:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0' <<<"$G")" 1
ck "malformed line skipped"  "$(grep -c 'malformed' <<<"$G")" 0
ck "no whole-line leak (no pipes in cred=)" "$(grep -c '^cred=.*|' <<<"$G")" 0
ck "domain=corp.local"       "$(grep -cxF 'domain=corp.local' <<<"$G")" 1
ck "dc_ip=10.10.11.10"       "$(grep -cxF 'dc_ip=10.10.11.10' <<<"$G")" 1

printf '  --- creds assertions: PASS=%d FAIL=%d ---\n' "$APASS" "$AFAIL"

bar "DONE  (mock root $TMP — cleaned on exit)"
[[ $AFAIL -eq 0 ]] || exit 1
exit 0
